[package]
name = "liquidity_math"
version = "0.1.0"
cairo-version = "2.0.1"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
orion = { git = "https://github.com/gizatechxyz/orion.git" }
starknet = "2.0.1"

